### ISSUE TITLE
Map mSupply consumption to eSIGL

### ISSUE THREAD

**Issue by wlthomson** [msupply-foundation/elmis-service#140]
Requested by IC:

> Consumption: sum of all consumptions at each ESPC of the District i.e. of all the client stores

#### Background

eSIGL supports the follow columns for reporting consumption for `fullSupplyLineItems`:

- `"Average Monthly Consumption (AMC)"` (`"Consommation Mensuelle Moyenne (CMM)"`)
-  "`Monthly Normalized Consumption (MNC)"` 
- `"Period Normalized Consumption (PNC)"`

Assuming the VM is up-to-date, the IC requisition template only reports data for `CMM`. 

The columns are calculated for each regimen line as follows:

- `MNC = (quantityDispensed * reportingDays) / (( M * 30 ) - stockOutDays) + (newPatientCount * (dosesPerMonth / dosesPerDispensingUnit))`
- `PNC  = MNC * M`
- `ACC = (MNC_g / N) + (MNC_(g-1) / N + .... + (MNC_(g-(g-1)) /  g`.

Variables have been substituted for the fields they represent. `M` and `g` represent quantities which are not clear from the eSIGL interface, but I think they represent the following:

- `M = numberOfMonths`
- `g = 3` (guessing this is lookback period, but it seems to be hardcoded).

eSIGL supports the following fields for `nonFullSuppliyLineItems`:

- `"amc": [number]`
- `"normalizedConsumption": [number]`

It's not quite clear why these fields only appear for `nonFullSupplyLineItems`, and neither of these fields can be displayed by any columns. Suspicion is that as `nonFullSupplyLineItems` may not be present on each requisition, eSIGL handles `AMC` differently than for `fullSupplyLineItems`?

#### Implementation

As `ACC` is directly calculated from historical data, there isn't really much we can do here. The API exposes `previousNormalizedConsumptions` in the following format:

```
"previousNormalizedConsumptions": [array<number>]
```

After saving the requisition with different values, the old values will still be returned, which suggests these values are read-only and cannot be modified by the user (possibly they are calculated by a query rather that being stored on the record?).

#### Follow up

Not really sure what we can do here. For now, the idea for this issue is mainly to ensure that @mark-prins has sufficient technical information available to him to be able to justify why we are pushing back on this requirement.

**Comment by wlthomson** [comment]
Update: added `nonFullSupplyLineItems` fields.

**Comment by wlthomson** [comment]
@andreievg @craigdrown @mark-prins @joshxg  I think this might provide some insights into ongoing discussion re. how to calculate AMC?

**Comment by mark-prins** [comment]
July 2021 meeting with JSI et al. 
Summary is that we should populate the field quantityDispensed. The _normalizedConsumption_ is a calculated field and should not be populated when submitting.

Note: there is [documentation via swagger](https://83.96.240.209/public/api-docs/index.html) available on the test vm

**Comment by wlthomson** [comment]
I'm a bit confused, as it seems we are already populating `quantityDispensed` from `outgoingStock` (where `outgoingStock` is calculated by the mSupply helper method `itemGetStockDetails`):

https://github.com/openmsupply/elmis-service/blob/e5a95411d662cc371998977f678dc7a57152ffb5/src/requisitionMerge.js#L19

**Comment by wlthomson** [comment]
Closing as agreed with @craigdrown.
