### ISSUE TITLE
Map mSupply days out of stock to eSIGL

### ISSUE THREAD

**Issue by wlthomson** [msupply-foundation/elmis-service#141]
Requested by IC: 

> Days out of Stock: days out of stock at the District store

#### Background

The eSIGL column `"Days Out of Stock"` (`"Nombre de jours de rupture (pharmacie)"`) displays data stored in the numerical field `stockOutDays`.

mSupply has the following DOS-related aggregation methods:

- `aggregator_getDOS`
- `aggregator_monthlyDOS`

Each mSupply `requisitionLine` also contains the (possibly unrelated?) numeric field `days_out_or_new_demand`.

####  Implementation

Nothing difficult here, just a mapping between the mSupply fielld and `stockOutDays`. AFAIK, there is some remaining discussion to be had regarding the calculation that IC want to be used?

**Comment by mark-prins** [comment]
Submitted a requisition, supplying a value for `stockOutDays` and this shows correctly in the resulting requisition.

**Comment by craigdrown** [comment]
Closing this @mark-prins  as any further work is on the mSupply side (Have made a note to capture that outstanding work)

**Comment by wlthomson** [comment]
@mark-prins Do you remember what you tested above? Did you mean you submitted via `elmis-service`, or directly to eSIGL?

@craigdrown If @mark-prins answer above is that he submitted successfully via the current `elmis-service`, the below can be ignored, otherwise:

From memory and a quick glace at the code, I don't think additional requisition line fields coming from mSupply will be merged into the requisition pushed to eSIGL unless they are included in [this mapping](https://github.com/openmsupply/elmis-service/blob/e5a95411d662cc371998977f678dc7a57152ffb5/src/requisitionMerge.js#L16) (see the [item merging routine](https://github.com/openmsupply/elmis-service/blob/e5a95411d662cc371998977f678dc7a57152ffb5/src/requisitionMerge.js#L265)).

> Implementation
> 
> Nothing difficult here, just a mapping between the mSupply fielld and stockOutDays. AFAIK, there is some remaining discussion to be had regarding the calculation that IC want to be used?

I wrote this more than a year ago, but I suspect this is what I was referring to here.

If I'm right, doing the mapping in mSupply will be insufficient as the data will be ignored even if the fields map identically. If this is the case, this issue will need to be re-openend and a mapping added between the mSupply requisition line field and `stockOutDays`.

**Comment by mark-prins** [comment]
@wlthomson yes, you've understood correctly. Sorry @craigdrown this needs to be reopened. 
What I was testing was that this is the correct field to use and that providing a value to it did in fact populate the requisition in eSIGL correctly.

I did not implement the mapping in the `elmis-service`, nor check that desktop is populating that property.

**Comment by wlthomson** [comment]
Looks like most likely contender here is `DOSforAMCadjustment` (capitalisation intentional). This is calculated and stored on the requisition line, so can be mapped directly to `stockOutDays` without requiring any changes to the mSupply codebase.

**Comment by wlthomson** [comment]
Fixed in [v0.6.0](2688c37da34dbb46f64b9b5b52d33b57657f57e0).
